### ISSUE TITLE
Tipo-g. La escuela de tipografía de Barcelona

### ISSUE THREAD

**Issue by LauraMeseguer** [justinpenner/type-design-resources#14]
Hello! I'd like you to consider adding our 
**Curso de diseño de tipografía. Del boceto a "Variable Fonts"** de Tipo-g 
in your list of courses [https://typedesignresources.com/?utm_source=substack&utm_medium=email#courses] 
It consists of a course of 248 hours, presential, not online, in Barcelona. The faculty is composed by a group of enthusiastic professionals who are well known in the international typographic scene.

Thank you! 

Tipo-g. La escuela de tipografía de Barcelona
[www.tipo-g.com](url)

**Comment by justinpenner** [comment]
Thanks, Laura! I've added it. My apologies for the slow response – GitHub was giving me certificate errors for the past week, which I just resolved this morning.
