### ISSUE TITLE
Adding FontArk font editor?

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#17]
Maybe it's worth adding FontArk to the ‘Free and open source (FOSS) font editors’ list:
[https://fontark.net/farkwp/](https://fontark.net/farkwp/)

**Comment by justinpenner** [comment]
Thanks, I haven't seen this one before. I've added it to the commercial font editors section. It looks like it's free while in beta, but it's not open-source.

**Comment by guillaumeberry** [comment]
✅
