### ISSUE TITLE
[Web-based proofing and testing] Fontbakery 🧑‍🍳

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#23]
Description:
Font Bakery is command-line tool for checking the quality of font projects.

The brand new online version (drag'n drop version):
[http://fontbakery.com/](http://fontbakery.com/)

The code-based version:
[https://github.com/fonttools/fontbakery](https://github.com/fonttools/fontbakery)

**Comment by justinpenner** [comment]
I'm sorry I missed this! I've just added it to a new [Font engineering](https://typedesignresources.com/#font-engineering) category along with a few other resources.
