### ISSUE TITLE
[Conferences / Events] 3 suggestions

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#24]
### Inscript 
[https://inscript.tf/](https://inscript.tf/)

Description:
A formative five-day festival showcasing inspiring presentations at the overlap of typography and today’s evolving industries, including: artificial, augmented, and virtual realities, creative computing, font specifications, and innovative use of craft.

### Fontstand conference
[https://fontstand.com/conference/](https://fontstand.com/conference/)

Description:
Annual typography conference organized by Fontstand, the typeface discovery and rental app.

### Kerning
[https://kerning.it/](https://kerning.it/)

Description:
Kerning is the first international conference in Italy dedicated solely to typography and web typography.

Although the conference stopped in 2019, the valuable talks are available online: https://vimeo.com/channels/kerning
Maybe one day the conf will be back…

**Comment by guillaumeberry** [comment]
Have another one to suggest! 😄

### Multilingüe
[https://www.typedrivesculture.com/](https://www.typedrivesculture.com/)

Description:
TDC's online conference on writing and typography for native languages from Latin America.

**Comment by justinpenner** [comment]
Thanks for all these great suggestions! I've added them to the site.
