### ISSUE TITLE
[Courses / Events] 2 suggestions

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#25]
### Type Electives

_To add in the events section?_
[https://www.typeelectives.com/events](https://www.typeelectives.com/events)

Description:
Co-founded by Lynne Yun and Juan Villanueva, Type Electives offers courses and events that go beyond traditional type design education.

### I Love Typography Academy (courses)
[https://ilovetypography.com/academy/courses/](https://ilovetypography.com/academy/courses/)

Description:
ILT academy exists to promote expert teaching of type design, font production, and typography. Courses cover various script systems and are taught in a number of languages.

**Comment by justinpenner** [comment]
Thanks, I've added these ones, too.
