### ISSUE TITLE
[Full-time programs] Master’s degree in Type Design ECAL

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#26]
### Master Type Design
[https://ecal.ch/en/courses-and-research/master/type-design/](https://ecal.ch/en/courses-and-research/master/type-design/)

Description:
Students work on techniques specific to typeface design (calligraphy, work on curves, construction, digital drawing), including the development of multi script font families.

**Comment by justinpenner** [comment]
ECAL is already listed in Full-time programs
<img width="780" alt="image" src="https://github.com/justinpenner/type-design-resources/assets/46039243/73167faa-8c89-4a82-96ea-d83e921926bc">

**Comment by guillaumeberry** [comment]
Oops, I was not paying enough attention 😅
