### ISSUE TITLE
[Web-based proofing and testing] Stack & Justify

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#29]
[https://max-esnee.com/stack-and-justify/](https://max-esnee.com/stack-and-justify/) by Max Esnée

- A tool to help create type specimens by finding words or phrases of the same width
- 16 languages available
- Similar to Waterfall by Mass Driver.

**Comment by justinpenner** [comment]
Looks like a fantastic tool. It's added now, thanks to @weiweihuanghuang.
