### ISSUE TITLE
Add OpenType programming documentation

### ISSUE THREAD

**Issue by simoncozens** [justinpenner/type-design-resources#4]
* [Fonts and Layout for Global Scripts](https://simoncozens.github.io/fonts-and-layout/)
* [The OpenType Cookbook](http://opentypecookbook.com)
* [OpenType Feature File specification](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html)

**Comment by justinpenner** [comment]
Thanks for filling that gap! I've added a new section for OpenType programming:
https://typedesignresources.com/#opentype-feature-programming
