### ISSUE TITLE
FontDev: new font tool

### ISSUE THREAD

**Issue by guillaumeberry** [justinpenner/type-design-resources#40]
**FontDev** by supa Olli Meier
—› [https://fontdev.app/](https://fontdev.app/)

Enables to view, edit and save font files tables + export modified files: right in the browser 🤯 😱 🔥

**Comment by justinpenner** [comment]
Very cool web app! I'm surprised I haven't heard about it.

**Comment by guillaumeberry** [comment]
@justinpenner it's very new I think, and Olli has been very productive lately (Fontra & this).
