### ISSUE TITLE
Use more impartial language when describing font editors?

### ISSUE THREAD

**Issue by colinmford** [justinpenner/type-design-resources#6]
On the whole, the language used in link descriptions on this site tend to be simple, informative and without marketing spin... except, it seems, when talking about font software.

Given the place this website has in informing new type designers on how to start, I think the language used to describe the editors in the Software section should be as informative as possible without engaging in marketing spin.

A good example of this is the Fontself description — it describes what it does without making any marketing claims:

> [Fontself](https://www.fontself.com/)
> Illustrator/Photoshop plugins to turn your designs into fonts.

However the description High Logic Font Creator takes marketing language directly from their homepage ("With over 5 million downloads to date, FontCreator is considered the world's most popular and best font editor."). The description for FontLab makes claims about its primacy ("Gold standard") which might have been true at one point but doesn't reflect the current editor landscape. They doesn't appear to be as impartial as other link descriptions on the page:

>[FontLab](https://www.fontlab.com/)
>The gold standard for type design software, and the longest history – first released in 1992.
>
> [High Logic Font Creator](https://www.high-logic.com/font-editor/fontcreator)
> The world’s most popular font editor

If you would appreciate a PR, I can attempt to write more neutral descriptions — otherwise I'll leave it with you, of course.

Either way, thanks for this wonderful resource!

**Comment by justinpenner** [comment]
I fully agree, Colin. Some of them were hastily written, or copied and pasted from the official sites. The High Logic description is supposed to have actual quotation marks around it – looks like I forgot to escape them and they are just being interpreted as YAML syntax:
```
          - name: High Logic Font Creator
            url: https://www.high-logic.com/font-editor/fontcreator
            description: "The world's most popular font editor"
```

I'd really be interested to read your descriptions of each font editor if/when you have time to submit a PR. Your view of the software landscape is probably a little different than mine, and I mainly use Glyphs, so you might have more experience with some of the other font editors.

**Comment by colinmford** [comment]
@justinpenner Thanks! See PR #11
